### ISSUE TITLE
Negative reviews without creating support requests

### ISSUE THREAD

**Issue by northernbeacheswebsites** [Clorith/wporg-support-guidelines#12]
As a plugin developer I am sick and tired of people leaving 1 star reviews when they have not first reached out to create a support ticket first.

By not removing these reviews it does the following:
1. It does not provide the plugin author with the opportunity to actually fix any issues that may exist with the plugin, and therefore the issue will remain and could occur for other users. So it's not helping the community or the plugin author.
2. Mentally it's not positive for plugin authors who spend weeks and months of their time on things and give them away for free for someone to go give them 1 star when the issue could actually be with them and their system or their understanding of WordPress or the plugin.
3. These reviews provide an inaccurate representation of the plugins utility because they aren't taking into account the ability of the plugin author to provide support and often these reviews are due to user error or understanding.

I understand that in a paid marketplace a star rating system makes sense, but in a free marketplace I believe a like system makes more sense.

I also want to note, that all my plugins make it super clear and easy for people to create support requests, yet this still happens. 

The thing is, I don't mind helping people even though it takes up my time which I give away freely to the WordPress community. But when I don't have the opportunity to do this and get some ungracious person leave a review without even seeking help it gets me very mad. So much so, that it's my new policy to not submit any more plugins to WordPress, that way I don't have to deal with these reviews.

I would encourage the moderators to reach out to the plugin developer community and get their feedback on this issue.

**Comment by Ipstenu** [comment]
I don't have to ask the plugin (or theme) devs to know they want fewer 'My review is really a support post' reviews. And for what it's worth, everyone wants that.

We don't remove them right now because if we do that it gives users a bad experience:

1. The community at large assumes we're removing reviews at the behest of the developer for a special favour (see the drama around Gutenberg reviews for an example)
2. The user's post vanishes and they don't understand why, and get no help, and hate you and the community 
3. It removes your ability to correct the issue entirely

The real problem here is management. Because unless someone writes the code to check 'Did this user already post in this plugin's support forum?' **or** someone writes a 'convert to support' trigger, then you're asking _volunteers_ to manage this for 55,000 plugins and 3000 themes. And that's really unreasonable and unmaintainable :(

Do you have any practical suggestions of how to process this? Because otherwise, the answer is "Yeah you're right it sucks. We hate it too."

**Comment by northernbeacheswebsites** [comment]
I would suggest at a minimum having a prompt so that if they select 1 star in the review that it prompts them with something saying "Are you experiencing an issue with the plugin? If you haven't already we recommend creating a support topic for the plugin so the developer can assist you with your experience/issue.".

**Comment by Ipstenu** [comment]
That then would be something for https://meta.trac.wordpress.org

Something automated is going to be better than a general guideline of "support before review" (which will be unenforceable at scale)

**Comment by Clorith** [comment]
This is more a task for a meta ticket as mentioned, as such I'm closing this out here.

It's worth noting that something automated looking for existing support topics isn't a viable option either, as we allow reviews based on premium upgrades if they upsell, but do not allow them to support the premium features on WordPress.org, so it creates a disconnect there.
